_target_: histomil2.Hydra_helper.opt_sch_part_helpers.opt_sch_config
metrics_names:
- MSE
- CosSim
metrics_paras:
  regression:
    MSE: {}
    CosSim:
      reduction: mean
loss_name: MSELoss
loss_paras:
  reduction: mean
optimizer_name_list:
- Adam
optimizer_paras_list:
- lr: 0.0001
scheduler_name_list:
- StepLR
scheduler_paras_list:
- step_size: 10
  gamma: 0.1
n_classes: null
