_target_: histomil2.Hydra_helper.model_part_helpers.model_config
encoder_name: hf-hub:bioptimus/H-optimus-0
encoder_output_dim: 1536
translate_module_name: MLP
translate_additional_params:
  mid_dim: 512  # MLP中间层维度
  peft_method: hra  # 使用HRA方法
  apply_GS: true  # 启用Gram-Schmidt正交化，可以提高模型性能
target_dim: ???
lora_r: 256  # HRA的秩，设置为偶数以便默认初始化方法工作
lora_alpha: 32  # 这个参数在HRA中不会被使用
lora_dropout: 0.1  # 这个参数在HRA中不会被使用
pre_trained_ckpt_path: null
