_target_: histomil2.Hydra_helper.model_part_helpers.model_config
encoder_name: hf-hub:bioptimus/H-optimus-0
encoder_output_dim: 1536
translate_module_name: Transformer
translate_additional_params:
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 2048
target_dim: ???
lora_r: 8
lora_alpha: 32
lora_dropout: 0.1
pre_trained_ckpt_path: null
