_target_: histomil2.Hydra_helper.trainer_part_helpers.trainer_config
entity: ???
exp_name: ???
task_type: ???
class_nb: ???
model_name: ???
ckpt_folder: ???
trainer_output_dir: ???
wandb_api_key: ???
project: HistoMIL2
clip_grad: 1.0
max_epochs: 10
additional_pl_paras: {}
with_logger: wandb
save_ckpt: true
ckpt_format: '{epoch:02d}-{val_CosineSimilarity:.2f}'
ckpt_para:
  save_top_k: 1
  mode: max
  monitor: val_CosineSimilarity
